language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
cache:
  bundler: true
  directories:
  - "${HOME}/bin"
  - nubis/librarian-puppet
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
    - libssl1.0.0
script:
- nubis/travis/run-checks
notifications:
  slack:
    secure: P0H0eoW4S3mQhSI9y2frXOVEWd/MhaUHSE9VpliNochCkaVbTJdj5F3TjzV6N083z+ocEhSGylEBF7r/E0F+avOHdouPrfrApXfVnI/E0vMePmgWyxriDagWX6DI8CGiNFu3uBfJnSO8xFR72/YN5YbiTiY14TP+TG+CcUrtgX8=
