language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
cache:
  bundler: true
  directories:
  - "${HOME}/bin"
  - nubis/librarian-puppet
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
script:
- nubis/travis/run-checks
notifications:
  slack:
    secure: iecp6/y9RfBk+DYdIlYHVw/4okQdeAejzO2pXVsnrBTSIBK8YH7W04UqJJJR1PaSuZutJFUSDV6QiWqHw3nv3a/4sFyLMifYO20jwfDtUN70RK+5/zJmCtBHft6Om9/q30gH1XhUA0jAwlFGQOgnepEC1Bdza4ovArjZFqnhPEAhKsYEfJUdmCr78CnxfsckTxTfI9jbQVcdn4O2ImvSsBD+Rr4pJktSom+4WhuwkbMucXYrNiPbFeMTfCnOVgnC0dBi5N/9Lhz2lKSnZdOY3pcXLkwB0NOef+d9LU8PAxQItgj7dIAmou2Ap9QU2N75pd+FvWWnjpWei87NI1KxQN9q6BXrdkAmCnxsP/mbEq0pBJWoL2otoLgYw1miCMnPiaICYLgkGWAuir6PrPCywCF6FHkEZtZvEkGr3GLbF2DUD3yG4jjk8Xv4t8CHFuAL1prm4aZa8G/cFNhQNZJ+oSAezMimffWJjMBm+a/7OHTbJfu4SNEWajmQkIUpKboVxtcBav5tHMstzmm7tfCzFwPs9C+wgHZbsUhyYOJhb5Inb/KfAm9UPiiI0XmM9KdJmGxqznbm3TcSrqxtNeR4AWmOQ8WiKnH/p12Uc4vlzTyrr0JS+SeC3wsPN/cfGvq2YiFCpKD3/NYYST+CEiw6pDCUE1ef/N2uYKWVItilFd4=
