language: ruby
sudo: false

gemfile: nubis/travis/Gemfile

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
  - "puppet-lint --no-80chars-check --no-140chars-check --fail-on-warnings nubis/puppet/*pp"
  - "find nubis/ -type f -print | xargs file | grep 'shell script' | cut -d: -f1 | xargs shellcheck"
