#!/bin/bash -l

set -e

rm -rf artifacts
mkdir artifacts

SKIP_BUILD=$(jq -rM '.variables.skip_build' nubis/builder/project.json)

# If there is a deploy_only variable don't do a build
if [ "${SKIP_BUILD}" == "true" ]; then
    echo "Skipping build"
    # jenkins gets grumpy if artifacts folder is empty
    # so we just add something here
    touch "artifacts/SKIP"
    exit 0
fi

NUBIS_ARENA=$(nubis-metadata NUBIS_ARENA)

ORIG_ALLOWED_TCP=$(consul kv get "nat/$NUBIS_ARENA/config/IptablesAllowTCP" 2>/dev/null || echo '[]')

# Add port 22 exception
NEW_ALLOWED_TCP=$(echo "$ORIG_ALLOWED_TCP" | jq -c '. |= .+ [22] | unique' )

consulate kv set "nat/$NUBIS_ARENA/config/IptablesAllowTCP" "$NEW_ALLOWED_TCP"

nubis-ctl --account "$(nubis-metadata NUBIS_ACCOUNT)" --local --skip-aws-vault builder build --color --instance-type c3.large --spot

consulate kv set "nat/$NUBIS_ARENA/config/IptablesAllowTCP" "$ORIG_ALLOWED_TCP"

if [ -d nubis/terraform ]; then
  rsync -av nubis/terraform artifacts/nubis/
fi

if [ -d nubis/proxy ]; then
  rsync -av nubis/proxy artifacts/nubis/
fi

if [ -d nubis/monitoring ]; then
  rsync -av nubis/monitoring artifacts/nubis/
fi

if [ -d nubis/builder/artifacts ]; then
  mkdir -p artifacts/builder/
  rsync -av nubis/builder/artifacts artifacts/nubis/builder/
fi
