forge "https://forgeapi.puppetlabs.com"

# Jenkins Dependencies
mod 'puppet/zypprepo', '2.2.0'
mod 'puppetlabs-transition', '0.1.1'

# Jenkins itself
mod 'rtyler/jenkins',
    :git => 'https://github.com/jenkinsci/puppet-jenkins.git',
    :ref => 'ffd12e3c12f6817bd34f67a6e041d29c53a68e36'

# Java
mod 'puppetlabs/java', '2.2.0'
