forge "https://forgeapi.puppetlabs.com"

# Jenkins Dependencies
mod 'puppet/zypprepo', '2.2.0'
mod 'puppetlabs-transition', '0.1.1'

# Jenkins itself
mod 'rtyler/jenkins',
    :git => 'https://github.com/jenkinsci/puppet-jenkins.git',
    :ref => '7fe3f909d6d26299e1ba78204ea1ee022cc75b6e'

# Java
mod 'puppetlabs/java', '2.2.0'

# Docker Dependencies
mod 'puppetlabs/translate', '1.0.0'
mod 'puppetlabs/stdlib', '4.24.0'

# Docker
mod 'puppetlabs/docker', '1.0.5'
