#!/bin/bash
set -e

env
ls $HOME/bin
find $HOME -name 'puppet-lint'

echo "Running Puppet Lint"
puppet-lint --no-80chars-check --no-140chars-check --fail-on-warnings nubis/puppet/*pp

echo "Running ShellCheck"
find nubis/ -type f -print | xargs file | grep 'shell script' | cut -d: -f1 | xargs shellcheck

echo "Running JSON Lint"
find nubis/ -name '*.json' | xargs jsonlint
